package com.shefamma.shefamma.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

@Component
@Data 
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ShefAmma")
public class AccountEntity {
    @DynamoDBHashKey(attributeName = "pk")
    private String phone;
//    @DynamoDBIndexHashKey(attributeName = "gpk2",globalSecondaryIndexName = "gsi2")
@DynamoDBIndexHashKey(attributeName = "gpk",globalSecondaryIndexName = "gsi1")
//    @DynamoDBRangeKey(attributeName = "sk")
    private String email;
//    @DynamoDBIndexRangeKey(attributeName = "gsk",globalSecondaryIndexName = "gsi")
    @DynamoDBAttribute(attributeName = "tmSt")
    private String timeStamp;
    @DynamoDBAttribute(attributeName = "pass")
    private String password;
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "uuid")
    private String uuid;
}
