package com.shefamma.shefamma.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

@Component
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ShefAmma")
public class GuestSignupEntity {
    @DynamoDBHashKey(attributeName = "pk")
    private String guestEmail;
    @DynamoDBRangeKey(attributeName = "sk")
    @DynamoDBIndexHashKey
    private String guestPhone;
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "gsk")
    private String timeStamp;
    @DynamoDBAttribute(attributeName = "pass")
    private String password;
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "uuid")
    private String guestUuid;
}
