package com.shefamma.shefamma.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

@Component
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ShefAmma")
public class GuestEntity {
    @DynamoDBHashKey(attributeName = "pk")
    @DynamoDBAutoGeneratedKey
    private String guestId;//h_id
    @DynamoDBRangeKey(attributeName = "sk")
    private String nameGuest;//hName
    @DynamoDBAttribute(attributeName = "eml")
    private String emailGuest;//hEmail
    @DynamoDBAttribute(attributeName = "phn")
    private String phone;//hPhone
    @DynamoDBAttribute(attributeName = "DP")
    private String DP;//hDP
    @DynamoDBAttribute(attributeName = "adr")
    private AdressSubEntity addressGuest;//hAdrress

}
