package com.shefamma.shefamma.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Component;
import lombok.Data;
import lombok.NoArgsConstructor;

@Component
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ShefAmma")
public class HostEntity {
    @DynamoDBHashKey(attributeName = "pk")
    @DynamoDBAutoGeneratedKey
    private String hostId;//h_id
    @DynamoDBRangeKey(attributeName = "sk")
    private String nameHost;//hName
    @DynamoDBAttribute(attributeName = "eml")
    private String emailHost;//hEmail
    @DynamoDBAttribute(attributeName = "phn")
    private String phone;//hPhone
    @DynamoDBAttribute(attributeName = "DDP")
    private String DDP;//DDP
    @DynamoDBAttribute(attributeName = "DP")
    private String DP;//hDP
    @DynamoDBAttribute(attributeName = "dsec")
    private String descriptionHost;//hDP
    @DynamoDBAttribute(attributeName = "adr")
    private AdressSubEntity addressHost;//hAdrress
    @DynamoDBAttribute(attributeName = "lat")
    private double latitude;
    @DynamoDBAttribute(attributeName = "long")
    private double longitude;
}
